# 1) Solve the below problem by using only numpy on tip data set


In [1]:
 import numpy as np
x = np.genfromtxt(r"C:\Users\user\Downloads\tipsf.csv",delimiter=",",skip_header = 1)
x

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [2]:
x.shape

(244, 8)

### 1. What is the total bill value?

In [3]:
a = x[:,1:2]
a
np.sum(a)

4827.77

### 2. What is the tip value?

In [4]:
b = x[:,2:3]
b
np.sum(b)

731.5799999999999

### 3. Count how many Sun,Sat,Thu,Fri are there.

In [5]:
c = x[:,5:6]
c
np.unique(c)

array([0., 1., 2., 3.])

In [6]:
np.unique(c,return_counts = True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

### 4. How many smokers are there?

In [7]:
d = x[:,4:5]
d
np.sum(d)

93.0

### 5. What is the average tip spent by male and female?

In [8]:
e = x[:,2:3]
e
np.mean(e)

2.99827868852459

### 6. How much amount have been spent by male and female?

In [9]:
f = x[:,1:3]
f
np.sum(f)

5559.35

### 7. What is the min and max tip given?

In [10]:
g = x[:,2:3]
g
np.max(g)

10.0

In [11]:
np.min(g)

1.0

### 8. How many male and female are going for dinner and lunch?

In [12]:
h = x[:,3:4]
h
np.sum(h)

157.0

### 9. Find out the average size.

In [13]:
i = x[:,7:]
i
np.mean(i)

2.569672131147541

### 10. How many male smokers and female smokers are there?

In [14]:
j = x[:,4:5]
j
np.unique(j)

array([0., 1.])

In [15]:
np.unique(j,return_counts = True)

(array([0., 1.]), array([151,  93], dtype=int64))

# 2)Solve the below problem by using only numpy functions on the  below given data set


In [16]:
import numpy as np

In [17]:
z = np.genfromtxt(r"C:\Users\user\Downloads\train_extended.csv",delimiter=",",skip_header = 1)
z

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [18]:
z.shape

(200000, 8)

### 1. What is the max and min length?

In [19]:
a = z[:, 0:1]
a

array([[1.575 ],
       [1.2375],
       [1.45  ],
       ...,
       [1.125 ],
       [1.625 ],
       [1.5875]])

In [20]:
np.max(a)

7.58349125

In [21]:
np.min(a)

0.0

### 2. Find out the difference between max and min length.

In [22]:
b = np.max(a) - np.min(a)
b

7.58349125

### 3. Find out coloumn wise average.

In [23]:
c = z[:,0:1]
c
np.mean(c)

1.3124480799562501

In [24]:
c1 = z[:,1:2]
c1
np.mean(c1)

1.020320357165

In [25]:
c2 = z[:,2:3]
c2
np.mean(c2)

0.34602787104999994

In [26]:
c3 = z[:,3:4]
c3
np.mean(c3)

23.123436312982403

In [27]:
c4 = z[:,4:5]
c4
np.mean(c4)

9.989370248049001

In [28]:
c5 = z[:,5:6]
c5
np.mean(c5)

4.993180956748749

In [29]:
c6 = z[:,6:7]
c6
np.mean(c6)

6.634229147607001

In [30]:
c7 = z[:,7:8]
c7
np.mean(c7)

9.950615

In [31]:
z

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

### 4. Find out all the age whose height is > 0.4.

In [66]:
d = z[:,2]  #height
d

array([0.375 , 0.375 , 0.4125, ..., 0.2875, 0.4125, 0.3875])

In [67]:
d > 0.4

array([False, False,  True, ..., False,  True, False])

In [68]:
d1 = z[:,7]   #age
d1

array([10., 19., 11., ...,  7., 11., 11.])

In [69]:
d1[d>0.4]

array([11., 14., 13., ..., 11., 11., 11.])

### 5. What is the average height and weight of the persons whose age is 10?

In [70]:
e = z[:,7]   #age
e

array([10., 19., 11., ...,  7., 11., 11.])

In [71]:
e2 = z[:,2]   #height
e2

array([0.375 , 0.375 , 0.4125, ..., 0.2875, 0.4125, 0.3875])

In [72]:
e3 = z[:,3]   #weight
e3

array([31.22697425, 21.885814  , 28.25027675, ..., 10.886208  ,
       33.89182725, 34.37376875])

In [73]:
e2 == 10

array([False, False, False, ..., False, False, False])

In [74]:
e3 ==10

array([False, False, False, ..., False, False, False])

In [75]:
np.mean(e2)

0.34602787104999994

In [76]:
np.mean(e3)

23.123436312982403

### 6. What is the total shell weight?

In [47]:
f = z[:,6:7]
f
np.sum(f)

1326845.8295214002

### 7. How many persons belongs to each and every unique age?

In [48]:
g = z[:,7:]
g

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [49]:
np.unique(g)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 29.])

In [50]:
np.unique(g,return_counts = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

### 8. What is the difference between shucked weight and viscara weight?

In [51]:
h = z[:,4:5]
h

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [52]:
h1 = z[:,5:6]
h1

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [53]:
h2 = h - h1
h2

array([[5.9817445],
       [3.855532 ],
       [4.1106775],
       ...,
       [2.9199985],
       [5.329706 ],
       [9.8372765]])

### 9. What is the average height of persons whose age is between 14 and 19?

In [54]:
i = z[:,7:]
i

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [55]:
i1 = np.where((i>14)&(i<19))
i1

(array([    15,     32,     38, ..., 199971, 199972, 199993], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [56]:
i2 = z[:,2:3]
i2

array([[0.375 ],
       [0.375 ],
       [0.4125],
       ...,
       [0.2875],
       [0.4125],
       [0.3875]])

In [57]:
i3 = i2.take(i1)
i3

array([[0.3875, 0.3625, 0.4   , ..., 0.35  , 0.4375, 0.375 ],
       [0.375 , 0.375 , 0.375 , ..., 0.375 , 0.375 , 0.375 ]])

In [58]:
np.mean(i3)

0.397035094637224

### 10. What is the average weight if we include shucked weight, viscera weight, shell weight?

In [59]:
j = z[:,4:5]
j

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [60]:
j1 = z[:,5:6]
j1

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [61]:
j2 = z[:,6:7]
j2

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [62]:
j3= j+j1+j2
j3

array([[28.2644515],
       [19.107563 ],
       [25.401152 ],
       ...,
       [10.0073735],
       [31.5529935],
       [33.395711 ]])

In [63]:
np.mean(j3)

21.616780352404746